---
title: "analysis"
format: html
editor: visual
editor_options: 
  chunk_output_type: inline
---

```{r}
library(ggplot2)
library(tidyverse)
```

```{r}
# loading in data sets
satresults <- read.csv("2012_SAT_Results_20260407.csv")

demographics <- read.csv("2006_-_2012_School_Demographics_and_Accountability_Snapshot_20260415.csv")
```

```{r}
# joining data sets by unique key "DBN"

data <- inner_join(demographics, satresults, by = "DBN")

```

```{r}
# filtering to year 2011/2012 and mutating a total SAT score variable
data <- data |>
  filter(schoolyear == 20112012) |> 
  mutate(SAT.Total =
    as.numeric(SAT.Critical.Reading.Avg..Score) +
    as.numeric(SAT.Math.Avg..Score) +
    as.numeric(SAT.Writing.Avg..Score))

# filtering out schools with N/A for SAT.Total variable

data <- data |>
  filter(!is.na(SAT.Total))
```

```{r}
# making SAT variables numeric
data <- data |>
  mutate(across(c(
    SAT.Critical.Reading.Avg..Score,
    SAT.Math.Avg..Score,
    SAT.Writing.Avg..Score
  ), ~as.numeric(.)))
```

```{r}
# selecting variables of interest
data <- data |>
select(DBN, Name, schoolyear, total_enrollment, SAT.Critical.Reading.Avg..Score, SAT.Math.Avg..Score, SAT.Writing.Avg..Score, Num.of.SAT.Test.Takers, male_num, male_per, female_num, female_per, black_num, black_per, white_num, white_per, hispanic_num, hispanic_per, asian_num, asian_per, selfcontained_num, ctt_num, sped_num, sped_percent, ell_num, ell_percent, SAT.Total)
```

Steph's Section: 

```{r}
# Analyzing SAT scores in a histogram

ggplot(data = data, aes(x = SAT.Total)) +
  geom_histogram() +
  labs(
    title = "Distrubution of SAT Scores Across NYC High Schools,\n2011 - 2012",
    x = "SAT Score",
    y = "# of Schools"
  ) +
  geom_vline(xintercept = mean(data$SAT.Total, na.rm = TRUE), color = "red") +
  theme_classic()
```
```{r}
# Analyzing SAT Scores in a summary table

library(gt)
summary_table <- tibble(
  Metric = c("Lowest SAT Score", "Highest SAT Score"),
  
  Score = c(
    min(data$SAT.Total, na.rm = TRUE),
    max(data$SAT.Total, na.rm = TRUE)
  ),
  
  School = c(
    data$Name[which.min(data$SAT.Total)],
    data$Name[which.max(data$SAT.Total)]
  ),
  
  Test_Takers = c(
    data$Num.of.SAT.Test.Takers[which.min(data$SAT.Total)],
    data$Num.of.SAT.Test.Takers[which.max(data$SAT.Total)]
  )
)

summary_table$School[is.na(summary_table$School)] <- "—"

summary_table |>
  gt() |>
  tab_header(
    title = "NYC High School SAT Scores (2011–2012)"
  ) |>
  cols_label(
    Metric = "Metric",
    Score = "SAT Score",
    School = "School Name",
    Test_Takers = "Number of Test Takers"
  ) |>
  fmt_number(
    columns = Score,
    decimals = 1
  ) |>
  tab_options(
    table.font.size = px(14)
  )
```


