---
title: "Data Tidying"
format: html
editor: visual
editor_options: 
  chunk_output_type: inline
---

```{r}
library(ggplot2)
library(tidyverse)
```

```{r}
# loading in data sets
satresults <- read.csv("2012_SAT_Results_20260407.csv")

demographics <- read.csv("2006_-_2012_School_Demographics_and_Accountability_Snapshot_20260415.csv")
```

```{r}
# joining data sets by unique key "DBN"

sat_data <- inner_join(demographics, satresults, by = "DBN")

```

```{r}
# filtering to year 2011/2012 and mutating a total SAT score variable
sat_data <- sat_data |>
  filter(schoolyear == 20112012) |> 
  mutate(SAT.Total =
    as.numeric(SAT.Critical.Reading.Avg..Score) +
    as.numeric(SAT.Math.Avg..Score) +
    as.numeric(SAT.Writing.Avg..Score))

# filtering out schools with N/A for SAT.Total variable

sat_data <- sat_data |>
  filter(!is.na(SAT.Total))
```

```{r}
# making SAT variables numeric
sat_data <- sat_data |>
  mutate(across(c(
    SAT.Critical.Reading.Avg..Score,
    SAT.Math.Avg..Score,
    SAT.Writing.Avg..Score
  ), ~as.numeric(.)))
```

```{r}
# mutating an English average SAT section
sat_data <- sat_data |>
  mutate(SAT.English = 
           as.numeric(SAT.Critical.Reading.Avg..Score)+
           as.numeric(SAT.Writing.Avg..Score))
```


```{r}
# selecting variables of interest
sat_data <- sat_data |>
select(DBN, Name, SAT.Critical.Reading.Avg..Score, SAT.Math.Avg..Score, SAT.Writing.Avg..Score, Num.of.SAT.Test.Takers, ctt_num, SAT.Total, SAT.English)
```

```{r}
# Creating csv of tidied data
write.csv(sat_data, "sat_data.csv", row.names = FALSE)
```
